### ISSUE TITLE
Wrong Stream Type prevents write

### ISSUE THREAD

**Issue by anthropos9** [thephpleague/flysystem-azure-blob-storage#16]
I'm trying to write an ImageMagick file using the `put` method. This is the error that is being reported:
> Argument 1 passed to MicrosoftAzure\Storage\Common\Internal\Utilities::isStreamLargerThanSizeOrNotSeekable() must be an instance of GuzzleHttp\Psr7\Stream, instance of GuzzleHttp\Psr7\PumpStream given, called in /app/vendor/microsoft/azure-storage-blob/src/Blob/BlobRestProxy.php on line 1841

Below is a screenshot of the debug panel. Not sure how to move forward with this bug. Please advise.
![Screenshot_2019-08-23 Argument 1 passed to MicrosoftAzure Storage Common Internal Utilities isStreamLargerThanSizeOrNotSeek](https://user-images.githubusercontent.com/3867685/63613786-60b8c980-c596-11e9-96ff-70505e33b539.png)

**Comment by anthropos9** [comment]
I managed to get it to work using this...
```php
$this->storage->put($path . $file, $newImg->__tostring());
```
Feels like there should be a better way of doing it, but for now it's working.

**Comment by frankdejonge** [comment]
Hi, unfortunately in PHP file handles and images share the type signifier, but Flysystem only works with file handles. Handling image manipulation streams is out of scope.
