### ISSUE TITLE
Has this been tested on Laravel 6.0?

### ISSUE THREAD

**Issue by wkopala** [thephpleague/flysystem-azure-blob-storage#17]
I recently updated to Laravel 6.0 and my image upload is no longer working. I'm wondering if I missed updating something on my end or if this is even updated for 6.0.

**Comment by frankdejonge** [comment]
Hi, this project does not need to be updated for Laravel 6 (or 7 now). What problem are you experiencing? Could you provide more details?

**Comment by wkopala** [comment]
Got it figured out. It’s actually an issue in the Microsoft/azure-storage-common code documentation. It says to set the proxy via the Laravel environment settings. But their code is using the flakey method of getenv(“HTTP_PROXY”) – which according to help docs doesn’t consistently work. There is a work around of using the $options array to send in the proxy, which is how I got it working (but this wasn’t in their documentation).

Thanks for getting back to me.

Cheers,
Wendy

**Comment by frankdejonge** [comment]
Thanks for the reply. I take it this issue can then be closed. Is that correct?
