### ISSUE TITLE
V2 support

### ISSUE THREAD

**Issue by Warxcell** [thephpleague/flysystem-azure-blob-storage#24]
Hello, any plans for support v2?

**Comment by OskarStark** [comment]
@frankdejonge I am curious, do yo plan to migrate this adapter to Flysystem 2? Otherwise I would be open to sponsor you if this will bring support for Azure 😄

**Comment by Warxcell** [comment]
> @frankdejonge I am curious, do yo plan to migrate this adapter to Flysystem 2? Otherwise I would be open to sponsor you if this will bring support for Azure

https://github.com/thephpleague/flysystem/pull/1277

**Comment by OskarStark** [comment]
Thanks!
