### ISSUE TITLE
Laravel get url of file path not supported from azure driver

### ISSUE THREAD

**Issue by kieran82** [thephpleague/flysystem-azure-blob-storage#26]
Everything works great but the function to get the file path gets an error saying not supported by the azure driver. This is the example that i was testing in laravel 8 with php 8

Storage::disk('azure')->url($path).

 this is the error message

"This driver does not support retrieving URLs.",

**Comment by frankdejonge** [comment]
This is a Laravel issue, not a Flysystem issue.

**Comment by kieran82** [comment]
thanks for getting back. Maybe laravel will fix this issue
