### ISSUE TITLE
Curl error 104 with big file

### ISSUE THREAD

**Issue by pimjansen** [thephpleague/flysystem-azure-blob-storage#27]
Hey,

I am trying to upload a backup file to the Azure blob storage (1.5G) however i receive below output after a while:
failed with message cURL error 56: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

```php
public function storeBackup(string $filePath, string $remotePathName): void
{
    $stream = fopen($filePath, 'rb+');
    $this->remoteFileSystem->writeStream(
        $remotePathName,
        $stream
    );
}
```

As far as i know there aren't any other ways to upload except this one. Any idea's on what this can be? It works with small files though but not with this one.

While debugging it actually ends up at the write itself.

Flysystem: 1.1.4
Adapter: 1.0.0

Best,
Pim

**Comment by frankdejonge** [comment]
Hi,

If you lookup the error, it's a cURL one that indicates there was a failure with receiving network data. This seems like perhaps an upper limit on what Azure allows? In any case, I currently don't have an inclination this is caused by Flysystem, so I'd recommend trying to recreate it with the azure clients underneath and opening an issue with the SDK.

**Comment by pimjansen** [comment]
Will do @frankdejonge. I started debugging and i see that some chunks fail and do not retry on the Azure SDK itself:

```
Fulfilled: 67
Fulfilled: 63
Fulfilled: 69
Fulfilled: 68
Denied: 76
GuzzleHttp\Exception\RequestException: cURL error 56: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:201
Stack trace:
#0 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
```
