### ISSUE TITLE
Adapter Flysystem V2

### ISSUE THREAD

**Issue by mschweiger90** [thephpleague/flysystem-azure-blob-storage#29]
Hello,

is there already an adapter for flysystem V2, e.g. like the V2 adapter for  AWS S3 here: https://flysystem.thephpleague.com/v2/docs/adapter/aws-s3-v3/

Thank you very much!

**Comment by ChristianVermeulen** [comment]
I am wondering the same. In order to upgrade to Symfony 6, we need to upgrade to Flysystem V2. But I highly doubt it..

**Comment by ChristianVermeulen** [comment]
I think we can close this, I have just upgrade to Flysystem V3 with [azure-blob-storage-adapter V3](https://github.com/thephpleague/flysystem-azure-blob-storage/releases/tag/3.0.9) and it all works like a charm!
