### ISSUE TITLE
Downgrade php version in composer.json

### ISSUE THREAD

**Issue by tourze** [thephpleague/flysystem-azure-blob-storage#30]
It is better to set the lowest php version to 7.2, because the lowest support in https://packagist.org/packages/league/flysystem#2.4.3 is 7.2.

**Comment by jaapdh** [comment]
This won't work since the code needs a higher version of PHP. So the current 3 version is incompatible with the version 2 of flysystem. Most adapters seem to have 2 major version at the moment. A version for flysystem:2.0 and a version for flysystem:3.0
