### ISSUE TITLE
Installation failed in php 7.2

### ISSUE THREAD

**Issue by phantanvietpk** [thephpleague/flysystem-azure-blob-storage#6]
I have install package via composer in php 7.2 , but i Installation failed .
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for league/flysystem-azure-blob-storage ^0.1.1 -> satisfiable by league/flysystem-azure-blob-storage[0.1.1].
    - league/flysystem-azure-blob-storage 0.1.1 requires phpunit/phpunit ^5.7 -> satisfiable by phpunit/phpunit[5.7.0, 5.7.1, 5.7.10, 5.7.11, 5.7.12, 5.7.13, 5.7.14, 5.7.15, 5.7.16, 5.7.17, 5.7.18, 5.7.19, 5.7.2, 5.7.20, 5.7.21, 5.7.22, 5.7.23, 5.7.24, 5.7.25, 5.7.26, 5.7.27, 5.7.3, 5.7.4, 5.7.5, 5.7.6, 5.7.7, 5.7.8, 5.7.9, 5.7.x-dev] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.`

**Comment by steffjenl** [comment]
this issue is now fixt in commit https://github.com/thephpleague/flysystem-azure-blob-storage/commit/fc1965e3ca5172cfcc6c349be948ce17c3740c96 and in versio 0.1.2 https://github.com/thephpleague/flysystem-azure-blob-storage/releases/tag/0.1.2
